import type { Testimonial } from "./site-config"

export const googleReviewsMeta = {
  rating: 5,
  totalCount: 39,
  source: "Google",
} as const

export const testimonials = [
  {
    quote: "Maya a été parfaite, elle s'adapte au demande des gens et prends des initiatives qui font que notre soirée de Noël fut une réussite...",
    author: "Luc Lepage",
    date: "il y a 6 mois",
    avatar: "/images/testimonials/luc-lepage.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Super Équipe on est toujours en confiance pour les spectacles",
    author: "Sébastien Loisirs",
    date: "il y a 6 mois",
    avatar: "/images/testimonials/sebastien-loisirs.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Excellent service.\nMerci pour le soutien aux organisations et aux artistes.",
    author: "Jimmy Haché",
    date: "il y a 7 mois",
    avatar: "/images/testimonials/jimmy-hache.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Je vous remercie infiniment, c'était mémorable. Caroline a une voix magnifique ! Je la recommande vivement !",
    author: "Julie",
    date: "il y a 8 mois",
    avatar: "/images/testimonials/julie.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Cette agence ne cesse de m’impressionner. Leurs musiciens sont des artistes d’un calibre exceptionnel, qui apportent talent, professionnalisme et une ambiance incroyable à chaque occasion. Qu’il s’agisse d’un rassemblement intime ou d’une grande célébration, ils arrivent toujours avec enthousiasme, une énergie formidable et un sens artistique qui élève toute l’expérience. Vraiment les meilleures vibes chaque fois!",
    author: "Cristine Toca",
    date: "il y a 1 mois",
    avatar: "/images/testimonials/cristine-toca.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Cela fait maintenant plus de 4 années que je prend des spectacles chez Agence Distinction pour mes différents besoins. Les spectacles sont même au delà de mes attentes vu la qualité débordante de talent chez cette agence d'artiste. Si on parle de mes besoins d'artistes en résidence ou en CHSLD, Agence distiction a toujours su deviner mes besoins. Je recommande à 100% !",
    author: "Portugais3000",
    date: "il y a 3 mois",
    avatar: "/images/testimonials/portugais3000.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Une grande variété d'artistes pour tous les occasions.\nEfficace, professionnel et courtois",
    author: "Joannie Laflamme",
    date: "il y a 4 mois",
    avatar: "/images/testimonials/joannie-laflamme.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Des voix vraiment magnifiques et un spectacle hautement apprécié.",
    author: "Carole Boivin",
    date: "il y a 4 mois",
    avatar: "/images/testimonials/carole-boivin.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Une excellente performance!\nJe recommande à 100% pour une magnifique soirée!",
    author: "Michele Guimond",
    date: "il y a 6 mois",
    avatar: "/images/testimonials/michele-guimond.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Sait la plus belle découverte que j’ai fait dans ma carrière de musicien cette agence contient que de bons chanteurs et musiciens professionnels et plusieurs autres talents merci la vie d’avoir placé cette agence sur mon chemin",
    author: "Carl Miousse",
    date: "il y a 8 mois",
    avatar: "/images/testimonials/carl-miousse.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Excellent service professionnel et efficace! Merveilleux artistes!",
    author: "Joanie Randlett",
    date: "il y a 8 mois",
    avatar: "/images/testimonials/joanie-randlett.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "quelle belle equipes ,depuis bientot 10 ans nous sommes avec cette belle equipes pour nos Évènements ,toujours un plaisir garantie ,merci a toute la belle gang et surtout a marie -josee pour cette joie et amour .",
    author: "olivia guyon",
    date: "il y a 8 mois",
    avatar: "/images/testimonials/olivia-guyon.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Sous la thématique brésilien nous avons adoré le ...band... qui à sût mettre une ambiance de feu dans notre établissement.",
    author: "Simon Maurer",
    date: "il y a 8 mois",
    avatar: "/images/testimonials/simon-maurer.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "J'ai demandé à l'agence distinction de me fournir 4 artistes pour des prestations dans mon CHSLD. La première m'a mis sous le charme, Miz Mia est venue chanter un excellent répertoire, elle accepte beaucoup de demande spéciales et fait réellement lever la fête. J'ai rarement eu l'occasion d'avoir autant de retour positif de mes résidents, des employés et même des familles qui ont adorés sont spectacle. Merci beaucoup Agence Distinction!",
    author: "Sebastien Fortin",
    date: "il y a 8 mois",
    avatar: "/images/testimonials/sebastien-fortin.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Belle diversité d'artistes pour touts occasions. Une agence à l'écoute de nos besoins, disponibles, professionnel et abordable.",
    author: "Cynthia Lafortune",
    date: "il y a 8 mois",
    avatar: "/images/testimonials/cynthia-lafortune.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Quel pur bonheur!! Des artistes de talents, mais également un service client généreux rempli de douceur.",
    author: "MC Divertissement vôtre",
    date: "il y a 8 mois",
    avatar: "/images/testimonials/mc-divertissement-votre.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Agence distinction, pour un événement réussi à coup sûr! Grande variété d’artistes!",
    author: "Kevin Cummings",
    date: "il y a 9 mois",
    avatar: "/images/testimonials/kevin-cummings.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Top agence! grand choix de super artistes ;-)",
    author: "Thomas Piche",
    date: "il y a 11 mois",
    avatar: "/images/testimonials/thomas-piche.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Très satisfait du spectacle que nous avons eu pour la st-jean. Les résidents ont beaucoup apprécier l'interprète.",
    author: "Catherine Asselin",
    date: "il y a 11 mois",
    avatar: "/images/testimonials/catherine-asselin.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "La meilleure agence de spectacles! Marie-Josée la proprio offre un service hors-pair, nous guide et nous conseille avec beaucoup de professionnalisme et de bonne humeur! De plus, les artistes qu’elle représente sont de grande qualité et variés! Pour un service sans tracas, c’est l’agence par excellence! Merci pour tout 🤩",
    author: "Cordeau Anye",
    date: "il y a 1 année",
    avatar: "/images/testimonials/cordeau-anye.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Chaque artiste que j'ai eu le plaisir de recevoir est rapidement devenu un véritable coup de cœur. Leur capacité à s'adapter à la clientèle et à créer une expérience unique et chaleureuse est remarquable. Merci pour leur professionnalisme et leur talent exceptionnel.",
    author: "léane thibaudeau",
    date: "il y a 1 année",
    avatar: "/images/testimonials/leane-thibaudeau.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Quelle belle expérience. Une très jolie voix. Marie José est avenante, comprehensive, et douce. Au reflets de ses chants. Merci pour ce partage intense en émotions",
    author: "letitom varin",
    date: "il y a 1 année",
    avatar: "/images/testimonials/letitom-varin.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Une agence extraordinaire qui offre des moments uniques et mémorables, tant pour les artistes que pour les résidents ✨🎶",
    author: "Jérémie Domenico",
    date: "il y a 1 année",
    avatar: "/images/testimonials/jeremie-domenico.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "toujours d'excellents artistes , tres humains. Ca fait du bien",
    author: "Stephane Descamps",
    date: "il y a 1 année",
    avatar: "/images/testimonials/stephane-descamps.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Ce sont les meilleurs !",
    author: "François Pelletier",
    date: "il y a 2 ans",
    avatar: "/images/testimonials/francois-pelletier.jpg",
    source: "Google",
    rating: 5,
  },
  {
    quote: "Excellente agence. Ils ont un choix varie. La personne au téléphone était super accueillante!",
    author: "Jessica Charland",
    date: "il y a 3 ans",
    avatar: "/images/testimonials/jessica-charland.jpg",
    source: "Google",
    rating: 5,
  },
] satisfies Testimonial[]
